FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/CoinChangeWizard-1.0-SNAPSHOT.jar /app/coinchange.jar
COPY src/main/resources/config.yml /app/config.yml

EXPOSE 8080

CMD ["java", "-jar", "/app/coinchange.jar", "server", "/app/config.yml"]